"""
Service configuration using environment variables.

Generated by appctl from app.manifest.yaml
"""

import os
from dataclasses import dataclass
from typing import Optional, Tuple
from functools import lru_cache


def _env(key: str, default: str = None) -> Optional[str]:
    """Get env var with _EXAMPLE_ prefix."""
    return os.environ.get(f"_EXAMPLE_{key}", os.environ.get(key, default))


def _env_bool(key: str, default: bool = False) -> bool:
    """Get boolean env var."""
    val = _env(key)
    if val is None:
        return default
    return val.lower() in ("true", "1", "yes")


def _env_int(key: str, default: int) -> int:
    """Get integer env var."""
    val = _env(key)
    return int(val) if val else default


@dataclass(frozen=True)
class Settings:
    """Application settings - frozen after creation."""
    # Service
    name: str
    version: str
    debug: bool
    host: str
    port: int
    
    # Database
    database_type: str
    database_name: str
    database_host: str
    database_port: Optional[int]
    database_user: Optional[str]
    database_password: Optional[str]
    
    # Redis
    redis_url: Optional[str]
    
    # Auth
    auth_enabled: bool
    allow_self_signup: bool
    jwt_secret: str
    jwt_expiry_hours: int
    
    # CORS
    cors_origins: Tuple[str, ...]


def _create_settings() -> Settings:
    """Create settings from environment."""
    cors = _env("CORS_ORIGINS", "*")
    cors_tuple = tuple(cors.split(",")) if cors else ("*",)
    
    return Settings(
        # Service
        name="_example",
        version=_env("VERSION", "1.0.0"),
        debug=_env_bool("DEBUG", False),
        host=_env("HOST", "0.0.0.0"),
        port=_env_int("PORT", 8000),
        
        # Database
        database_type=_env("DATABASE_TYPE", "sqlite"),
        database_name=_env("DATABASE_NAME", "./data/app.db"),
        database_host=_env("DATABASE_HOST", "localhost"),
        database_port=_env_int("DATABASE_PORT", None),
        database_user=_env("DATABASE_USER", None),
        database_password=_env("DATABASE_PASSWORD"),
        
        # Redis
        redis_url=_env("REDIS_URL"),
        
        # Auth
        auth_enabled=_env_bool("AUTH_ENABLED", True),
        allow_self_signup=_env_bool("ALLOW_SELF_SIGNUP", False),
        jwt_secret=_env("JWT_SECRET", "change-me-in-production"),
        jwt_expiry_hours=_env_int("JWT_EXPIRY_HOURS", 24),
        
        # CORS
        cors_origins=cors_tuple,
    )


@lru_cache()
def get_settings() -> Settings:
    """Get settings instance (cached, frozen)."""
    return _create_settings()
