"""
Database schema for _example.

Generated by appctl from app.manifest.yaml

Tables:
- items
"""

from typing import Any


async def init_schema(db: Any) -> None:
    """
    Initialize database schema.
    
    Called by kernel after database connection established.
    """
    # Item
    await db.execute("""
        CREATE TABLE IF NOT EXISTS items (
        id TEXT PRIMARY KEY,
        title TEXT,
        description TEXT,
        price REAL,
        active INTEGER DEFAULT True,
        workspace_id TEXT,
        created_at TEXT,
        updated_at TEXT,
        deleted_at TEXT
        )
    """)
    await db.execute("CREATE INDEX IF NOT EXISTS idx_items_workspace ON items(workspace_id)")
