"""
My example service

Generated by appctl from app.manifest.yaml
"""

from pathlib import Path
from typing import Tuple

from backend.app_kernel import (
    create_service,
    ServiceConfig,
    get_logger,
)

from .config import get_settings
from .db_schema import init_schema

from .routes.items import router as items_router


# =============================================================================
# Health Checks
# =============================================================================

async def check_database() -> Tuple[bool, str]:
    """Health check for database connection."""
    try:
        from backend.app_kernel.db import get_db_manager
        db_manager = get_db_manager()
        async with db_manager as conn:
            await conn.execute("SELECT 1", ())
        return True, "database connected"
    except Exception as e:
        return False, f"database error: {e}"



# =============================================================================
# Lifecycle
# =============================================================================

async def on_startup():
    """Initialize app-specific dependencies."""
    logger = get_logger()
    logger.info("_example started")


async def on_shutdown():
    """Cleanup on shutdown."""
    get_logger().info("_example shutting down")


# =============================================================================
# Config Builder
# =============================================================================

def _build_config() -> ServiceConfig:
    """Build ServiceConfig from settings."""
    settings = get_settings()
    return ServiceConfig(
        # Auth
        jwt_secret=settings.jwt_secret,
        jwt_expiry_hours=settings.jwt_expiry_hours,
        auth_enabled=settings.auth_enabled,
        allow_self_signup=settings.allow_self_signup,
        
        # Redis
        redis_url=settings.redis_url,
        redis_key_prefix="_example:",
        
        # Database
        database_name=settings.database_name,
        database_type=settings.database_type,
        database_host=settings.database_host,
        database_port=settings.database_port,
        database_user=settings.database_user,
        database_password=settings.database_password,
        
        # CORS
        cors_origins=list(settings.cors_origins),
        cors_credentials=True,
        
        # Debug
        debug=settings.debug,
        log_level="DEBUG" if settings.debug else "INFO",
    )


# =============================================================================
# Create App
# =============================================================================

def create_app():
    """Create the FastAPI application."""
    settings = get_settings()
    
    
    app = create_service(
        name="_example",
        version=settings.version,
        description=__doc__,
        
        # Routes
        routers=[
            items_router,
        ],
        
        # Background tasks
        tasks=None,
        
        # Configuration
        config=_build_config(),
        
        # Database schema
        schema_init=init_schema,
        
        # Lifecycle
        on_startup=on_startup,
        on_shutdown=on_shutdown,
        
        # Health checks
        health_checks=[check_database],
    )
    
    return app


# Create app instance
app = create_app()


if __name__ == "__main__":
    import uvicorn
    settings = get_settings()
    uvicorn.run("_example.main:app", host=settings.host, port=settings.port, reload=settings.debug)
