"""
Pydantic schemas for _example.

Generated by appctl from app.manifest.yaml
"""

from typing import Optional, List, Any
from datetime import datetime
from pydantic import BaseModel, Field


# Item schemas
class ItemCreate(BaseModel):
    title: str
    description: Optional[str] = None
    price: float
    active: bool


class ItemUpdate(BaseModel):
    title: Optional[str] = None
    description: Optional[str] = None
    price: Optional[float] = None
    active: Optional[bool] = None


class ItemResponse(BaseModel):
    id: str
    title: str
    description: Optional[str]
    price: float
    active: bool
    workspace_id: Optional[str] = None
    created_at: Optional[str] = None
    updated_at: Optional[str] = None
    
    class Config:
        from_attributes = True
