# Dockerfile.opensearch
FROM opensearchproject/opensearch:2.8.0

ENV discovery.type=single-node \
    DISABLE_SECURITY_PLUGIN=true \
    DISABLE_INSTALL_DEMO_CONFIG=true \
    OPENSEARCH_JAVA_OPTS="-Xms512m -Xmx512m" \
    bootstrap.memory_lock=false

EXPOSE 9200 9600