"""
CRUD routes for item.

Generated by appctl from app.manifest.yaml
"""

from typing import List, Optional
from fastapi import APIRouter, Depends, HTTPException, Query

from backend.app_kernel.db import db_session_dependency, AsyncConnection
from backend.app_kernel.auth import get_current_user, UserIdentity
from backend.app_kernel.access import require_workspace_member

from ..schemas import ItemCreate, ItemUpdate, ItemResponse


router = APIRouter(prefix="/items", tags=["items"])


@router.post("", response_model=ItemResponse, status_code=201)
async def create_item(
    data: ItemCreate,
    db: AsyncConnection = Depends(db_session_dependency),
    user: UserIdentity = Depends(get_current_user),
    workspace_id: str,
):
    """Create a new item."""
    import uuid
    from datetime import datetime, timezone
    
    entity = {
        "id": str(uuid.uuid4()),
        **data.model_dump(),
        "workspace_id": workspace_id,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    
    await db.save_entity("items", entity)
    return entity


@router.get("", response_model=List[ItemResponse])
async def list_items(
    db: AsyncConnection = Depends(db_session_dependency),
    user: UserIdentity = Depends(get_current_user),
    workspace_id: str,
    limit: int = Query(default=100, le=1000),
    offset: int = Query(default=0, ge=0),
):
    """List items."""
    filters = {"workspace_id": workspace_id, "deleted_at": None}
    entities = await db.find_entities("items", filters, limit=limit, offset=offset)
    return entities


@router.get("/{id}", response_model=ItemResponse)
async def get_item(
    id: str,
    db: AsyncConnection = Depends(db_session_dependency),
    user: UserIdentity = Depends(get_current_user),
    workspace_id: str,
):
    """Get a item by ID."""
    entity = await db.get_entity("items", id)
    if not entity:
        raise HTTPException(status_code=404, detail="Item not found")
    if entity.get("workspace_id") != workspace_id:
        raise HTTPException(status_code=403, detail="Access denied")
    return entity


@router.put("/{id}", response_model=ItemResponse)
async def update_item(
    id: str,
    data: ItemUpdate,
    db: AsyncConnection = Depends(db_session_dependency),
    user: UserIdentity = Depends(get_current_user),
    workspace_id: str,
):
    """Update a item."""
    from datetime import datetime, timezone
    
    entity = await db.get_entity("items", id)
    if not entity:
        raise HTTPException(status_code=404, detail="Item not found")
    if entity.get("workspace_id") != workspace_id:
        raise HTTPException(status_code=403, detail="Access denied")
    
    updated = {
        **entity,
        **data.model_dump(exclude_unset=True),
        "updated_at": datetime.now(timezone.utc).isoformat(),
    }
    
    await db.save_entity("items", updated)
    return updated


@router.delete("/{id}", status_code=204)
async def delete_item(
    id: str,
    db: AsyncConnection = Depends(db_session_dependency),
    user: UserIdentity = Depends(get_current_user),
    workspace_id: str,
):
    """Delete a item."""
    from datetime import datetime, timezone
    
    entity = await db.get_entity("items", id)
    if not entity:
        raise HTTPException(status_code=404, detail="Item not found")
    if entity.get("workspace_id") != workspace_id:
        raise HTTPException(status_code=403, detail="Access denied")
    
    entity["deleted_at"] = datetime.now(timezone.utc).isoformat()
    await db.save_entity("items", entity)
